### ISSUE TITLE
Request failed, status 429

### ISSUE THREAD

**Issue by zoltok** [clairefro/obsidian-chat-cbt-plugin#8]
I'm having trouble getting the plugin to work - I keep getting the error message `Chat CBT failed :( Request failed, status 429`. Any troubleshooting suggestions for getting it working? TIA!

**Comment by zoltok** [comment]
For sure. I'm using the OpenAI mode (I put in my API key), and both commands are giving the same error. I can't get it working on any note - I tried one with just text, one with tags, and it seems to be the same error for all. I'm new-ish to Obsidian, not logged in, if that's a factor. 

<img width="1093" alt="Screenshot 2024-01-03 at 12 29 24 PM" src="https://github.com/clairefro/obsidian-chat-cbt-plugin/assets/925798/e73855ec-1503-4661-a441-bcfe052866e1">

**Comment by clairefro** [comment]
Noted! 429 error is suggesting this error is coming from OpenAI side. 

It looks like you are using a valid API Key (otherwise it would be a 401/403/400), so I wonder if any of the following apply: 

- your API key is from an OpenAI account without a credit card attached to it yet 
- you've exceeded rate limit on calls to OpenAI 
- you've exceeding a monthly spending cap you've set for your yourself (see your usage dashboard)

Are you able to use this API Key to make a call successfully in other contexts?  

Also, with OpenAI there are [multiple reasons](https://help.openai.com/en/articles/6891829-error-code-429-rate-limit-reached-for-requests) for 429 errors. You might be able to see more details on the error in ChatCBT by opening the devloper console. while in obsidian, you can access dev tools with Cmd + Opt + I (on mac) or Ctr + Shift + I (on other) and try running the request to see the Console error. This might inform where the issue is precisely (or not - which means I ought to update error handling :) )

<img width="958" alt="image" src="https://github.com/clairefro/obsidian-chat-cbt-plugin/assets/9841162/f83ce960-abfc-4a67-8ad1-a35b77bf59de">



Let me know if you still get stuck and I can look into it further

**Comment by zoltok** [comment]
Oh, this is extremely helpful. I'll look into all this and report back, I really appreciate it!

**Comment by zoltok** [comment]
Okay, a quick update: this is user error. :) I have a ChatGPT subscription and wrongly assumed the same payment method I use for the subscription would be applied for API usage, but it's not. Once I added a payment method to the API billing settings everything worked perfectly. Thanks for the troubleshooting!

**Comment by clairefro** [comment]
Ah ha! glad to hear it is resolved :) 

To ease your worries, using the API is quite cheap in my experience, with the default model for ChatCBT: `chat-gpt-3.5-turbo`. It works very will with this, and costs so little (less than 2cents for full journaling session with summarization) that it is often more expensive for OpenAI to bill you and I think some months they don't even take my money :P

If you don't want to pay anything extra, you can try the local models with Ollama mode. I'll admit - it isn't quite as great quality or speed (yet) as `chat-gpt-3.5-turbo` with OpenAI, but is free.
